production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false

review:
  auto_deploy_on: pr
  environment: pr-${{ pr }}
  transient_environment: true
  production_environment: false

